apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "reflector.fullname" . }}-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "1"
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
