apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "reflector.fullname" . }}-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "3"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "reflector.fullname" . }}-certgen
subjects:
- kind: ServiceAccount
  name: {{ include "reflector.fullname" . }}-certgen
  namespace: {{ .Release.Namespace }}
