apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "reflector.fullname" . }}-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "2"
  labels:
    {{- include "reflector.labels" . | nindent 4 }}
