{{ if eq .Values.crd.install true }}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: reflects.k8s.karimi.dev
spec:
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                namespaces:
                  type: array
                  items:
                    type: string
                items:
                  type: array
                  items:
                    type: object
                    x-kubernetes-embedded-resource: true
                    x-kubernetes-preserve-unknown-fields: true
  group: k8s.karimi.dev
  names:
    plural: reflects
    kind: Reflect
    singular: reflect
    shortNames:
      - ref
      - rf
      - rfl
      - rfct
      - rft
  # preserveUnknownFields: false
{{ end }}
