# Default values for reflector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/mhkarimi1383/reflector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion (for example latest or main).
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

logLevel: info # one of debug, info, error
logType: text # could be text, json, or color

crd:
  install: true

role:
  clusterRoleName: cluster-admin # You can change that to any cluster role that matches requirements but since we want to handle everything, we will use cluster-admin by default

certGen:
  image:
    repository: docker.io/jettech/kube-webhook-certgen
    pullPolicy: IfNotPresent
    tag: "v1.5.2"

extraEnv: []
  # - name: TZ
  #   value: Asia/Tehran

serviceAccount:
  annotations: {}
  # Overrides default name for service account
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 443 # Note that connection is HTTPS

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
